/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import * as client from "../../client";
import { Quiz, Question } from "../../types";
import { Button, Card, Form, Alert } from "react-bootstrap";
import { FaCheckCircle, FaTimesCircle } from "react-icons/fa";

export default function QuizTake() {
  const { qid } = useParams();
  const searchParams = useSearchParams(); // To check if viewing past results
  const router = useRouter();
  const [quiz, setQuiz] = useState<Quiz | null>(null);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [answers, setAnswers] = useState<Record<string, any>>({});
  const [submitted, setSubmitted] = useState(false);
  const [score, setScore] = useState(0);
  const [loading, setLoading] = useState(true);

  // Mock User - in real app, get from context/session
  const currentUser = { _id: "123", username: "student1", role: "STUDENT" };

  useEffect(() => {
    const init = async () => {
      if (!qid) return;
      try {
        const q = await client.findQuizById(qid as string);
        setQuiz(q);
        setQuestions(q.questions || []);

        // Check if we are viewing a past submission
        // We can use a query param or just check if the user has no attempts left?
        // But the user might want to view results even if they have attempts left.
        // Let's assume ?mode=result triggers view mode.
        // Or we can check if there's a latest submission and we are NOT explicitly starting a new one?
        // Let's keep it simple: The 'Start Quiz' button on Details page sends us here.
        // If we want to view results, the 'View Results' button sends us here with ?mode=result.

        // Actually, if we just submitted, we stay here in 'submitted' state.

        // If coming from 'View Results', we should fetch the latest submission.
        // Let's handle ?submissionId=latest or similar.
        // Or simply ?view=true

        // However, if we are here to take the quiz, we should start fresh.

        // Let's check for existing submission to enforce attempt limits if we are trying to take it?
        // The Details page should guard this, but good to double check.

        // Logic:
        // If searchParams.get("view") === "true", fetch latest submission and show it.
        // Else, render empty form.

        // BUT, what if I reload the page after submitting?
        // Persistence of the *current* session is not required by prompt ("answers ... stored per student so that they can come back later").
        // "Later" implies looking at the record.

        if (searchParams.get("view") === "true") {
          const sub = await client.findLatestSubmission(
            qid as string,
            currentUser.username
          );
          if (sub) {
            setSubmitted(true);
            setScore(sub.score);
            // Map answers to state
            // sub.answers is [{ questionId, answer, ... }]
            // We need to map it back to our index-based or ID-based state.
            // My questions don't have IDs in the prompt description necessarily, but Mongoose gives them _id.
            // Let's assume index alignment or use _id if available.
            // In my schema/editor, questions are in an array.

            const loadedAnswers: Record<string, any> = {};
            sub.answers.forEach((ans: any) => {
              // Find index of question
              const idx = q.questions.findIndex(
                (quest: any) =>
                  quest._id === ans.questionId || quest._id === ans._id
              );
              // Note: The submission schema I created stores questionId.
              // The quiz questions likely have _id generated by Mongoose subdocuments.

              if (idx !== -1) {
                loadedAnswers[idx] = ans.answer;
              } else {
                // Fallback to index if questionId match fails (e.g. if questions were reordered? No, that breaks history).
                // Let's just rely on index for now if IDs are tricky, but IDs are safer.
                // The prompt didn't strictly specify question IDs management in Editor, but Mongoose adds them.
                // Let's assume we used IDs.
              }
            });

            // If we can't match by ID (e.g. old data), maybe try index?
            // For this assignment, simple index matching might suffice if we store it.
            // But my backend schema stores `questionId`.
            // I will try to match by ID.

            // Wait, the backend submission schema I saw in summary:
            // answers: [{ questionId: String, answer: Mixed, ... }]

            // So I need to make sure I send questionId when submitting.

            const mappedAnswers: Record<string, any> = {};
            sub.answers.forEach((a: any) => {
              // We need to find the index to control the inputs
              const qIndex = q.questions.findIndex(
                (quest: any) => quest._id === a.questionId
              );
              if (qIndex >= 0) {
                mappedAnswers[qIndex] = a.answer;
              }
            });
            setAnswers(mappedAnswers);
          }
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    init();
  }, [qid, searchParams, currentUser.username]);

  const handleAnswerChange = (questionIndex: number, answer: any) => {
    setAnswers({ ...answers, [questionIndex]: answer });
  };

  const handleSubmit = async () => {
    if (!quiz) return;
    // Calculate score locally for display, but backend should ideally verify.
    // The prompt says "Persist ... answers and scores".
    // I will calculate score here and send it, OR send answers and let backend calculate.
    // My backend schema requires 'score' in the body?
    // Let's check schema... "score: { type: Number, required: true }"
    // So frontend calculates score.

    let totalScore = 0;
    const submissionAnswers: any[] = [];

    quiz.questions.forEach((q, index) => {
      const userAnswer = answers[index];
      let isCorrect = false;
      let points = 0;

      if (
        q.questionType === "MULTIPLE_CHOICE" ||
        q.questionType === "TRUE_FALSE"
      ) {
        const correctChoice = q.choices.find((c) => c.isCorrect);
        if (correctChoice && userAnswer === correctChoice.text) {
          isCorrect = true;
        }
      } else if (q.questionType === "FILL_IN_BLANK") {
        const correctChoice = q.choices.find(
          (c) => c.text.toLowerCase() === (userAnswer || "").toLowerCase()
        );
        if (correctChoice) {
          isCorrect = true;
        }
      }

      if (isCorrect) {
        points = q.points;
        totalScore += points;
      }

      submissionAnswers.push({
        questionId: q._id, // Mongoose subdoc ID
        answer: userAnswer,
        isCorrect,
        points,
      });
    });

    try {
      await client.createSubmission(qid as string, {
        quizId: qid,
        username: currentUser.username,
        score: totalScore,
        answers: submissionAnswers,
      });
      setScore(totalScore);
      setSubmitted(true);
    } catch (err) {
      console.error("Error submitting quiz:", err);
    }
  };

  if (loading) return <div>Loading...</div>;
  if (!quiz) return <div>Quiz not found</div>;

  return (
    <div className="container mt-4" id="wd-quiz-take">
      <h3>{quiz.title}</h3>
      {submitted && (
        <Alert variant="info">
          <h4>Quiz Results</h4>
          <p>
            Your Score: {score} / {quiz.points}
          </p>
          {searchParams.get("view") === "true" && <p>Viewing past attempt.</p>}
        </Alert>
      )}

      {questions.map((q: Question, index: number) => {
        // Determine if we show validation
        const showValidation = submitted;
        const userAnswer = answers[index];

        // Helper to check correctness for display
        let isCorrect = false;
        if (
          q.questionType === "MULTIPLE_CHOICE" ||
          q.questionType === "TRUE_FALSE"
        ) {
          const correctChoice = q.choices.find((c) => c.isCorrect);
          if (correctChoice && userAnswer === correctChoice.text)
            isCorrect = true;
        } else if (q.questionType === "FILL_IN_BLANK") {
          const correctChoice = q.choices.find(
            (c) => c.text.toLowerCase() === (userAnswer || "").toLowerCase()
          );
          if (correctChoice) isCorrect = true;
        }

        return (
          <Card key={index} className="mb-4">
            <Card.Header className="d-flex justify-content-between align-items-center">
              <div className="d-flex align-items-center">
                {showValidation &&
                  (isCorrect ? (
                    <FaCheckCircle className="text-success me-2" />
                  ) : (
                    <FaTimesCircle className="text-danger me-2" />
                  ))}
                <h5>{q.title}</h5>
              </div>
              <span>{q.points} pts</span>
            </Card.Header>
            <Card.Body>
              <Card.Text
                dangerouslySetInnerHTML={{ __html: q.questionText || "" }}
              />

              {q.questionType === "MULTIPLE_CHOICE" && (
                <Form>
                  {q.choices.map((choice, i) => (
                    <Form.Check
                      key={i}
                      type="radio"
                      label={choice.text}
                      name={`question-${index}`}
                      onChange={() => handleAnswerChange(index, choice.text)}
                      disabled={submitted}
                      checked={answers[index] === choice.text}
                      // We can highlight specific choices if we want
                      className={
                        submitted && choice.isCorrect
                          ? "text-success fw-bold"
                          : submitted &&
                            !isCorrect &&
                            answers[index] === choice.text
                          ? "text-danger"
                          : ""
                      }
                    />
                  ))}
                </Form>
              )}

              {q.questionType === "TRUE_FALSE" && (
                <Form>
                  {q.choices.map((choice, i) => (
                    <Form.Check
                      key={i}
                      type="radio"
                      label={choice.text}
                      name={`question-${index}`}
                      onChange={() => handleAnswerChange(index, choice.text)}
                      disabled={submitted}
                      checked={answers[index] === choice.text}
                    />
                  ))}
                </Form>
              )}

              {q.questionType === "FILL_IN_BLANK" && (
                <div>
                  <Form.Control
                    type="text"
                    placeholder="Enter your answer"
                    onChange={(e) => handleAnswerChange(index, e.target.value)}
                    disabled={submitted}
                    value={answers[index] || ""}
                    isInvalid={submitted && !isCorrect}
                    isValid={submitted && isCorrect}
                  />
                  {submitted && !isCorrect && (
                    <div className="text-success mt-1">
                      Correct Answer(s):{" "}
                      {q.choices.map((c) => c.text).join(", ")}
                    </div>
                  )}
                </div>
              )}
            </Card.Body>
          </Card>
        );
      })}

      {!submitted && (
        <div className="d-flex justify-content-end mb-5">
          <Button variant="primary" onClick={handleSubmit} className="w-100">
            Submit Quiz
          </Button>
        </div>
      )}

      {submitted && (
        <div className="d-flex justify-content-end mb-5">
          <Button
            variant="secondary"
            onClick={() => router.back()}
            className="w-100"
          >
            Back to Details
          </Button>
        </div>
      )}
    </div>
  );
}
